### ISSUE TITLE
Not working with a filtering egress proxy

### ISSUE THREAD

**Issue by ijmad** [mknj/node-keepalive-proxy-agent#36]
Hello,

Great little library, solves my concerns about performance without keep-alives very nicely!

I'm working in an environment where Squid is set up to conditionally allow egress to particular URLs for security. This library works perfectly for URLs that are on the allowlist and can be accessed, but doesn't work for URLs that are blocked.

When squid responds with a block, it returns a 403 response to the CONNECT request, which includes a body. So the request does not end just with the headers block. 

I've looked at the source and it appears this is the culprit:

```
if (!response.endsWith("\r\n\r\n")) {
   return;
}
```

I believe this would be fixed by changing to the following:

```
if (response.indexOf("\r\n\r\n") < 0) {
   return;
}
```

So you just wait for the headers block, ignoring the body, but allowing it to end up in the buffer if it comes through.

Can I raise a pull request with this fix + I could try and write a test case if you like?

**Comment by mknj** [comment]
please give it a try and raise a pull request.
