### ISSUE TITLE
proxy hostname only works as host on node 8.X.X

### ISSUE THREAD

**Issue by javierblancosp** [mknj/node-keepalive-proxy-agent#8]
Hi,

I'm having a problem with node 8.x.x, if i set manually the proxy settings:
```js
    agent: new Agent({
      proxy: {
        host:'MYPROXYURL',
        port: '3128'
      }
    })
```
The request are working, but using your library with the https_proxy env variables, the request are not working.
I taked a look at your code and you are setting hostname instead of host, it seems that for node 8 hostname is not working.

BTW: nice library ;)

**Comment by mknj** [comment]
i don't want to support the old node version

**Comment by TimtationOne** [comment]
I somehow face the same issue.
Tested it with node version v14.15.4 and v15.6.0.
I'm using version v1.2 of the node-keepalive-proxy-agent.

Everything is okay when I use host instead of hostname.
Does anybody has an idea why this can happen?

**Comment by mknj** [comment]
Can you provide a code sample to reproduce your problem?
Can you compare the result to version 1.1.1? (npm i keepalive-proxy-agent@1.1.1)
Please open a new issue if you have a code sample.
